kind: pipeline
type: docker
name: default

steps:
  - name: docker build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: stiforr/ci-tools
      auto_tag: true
      tags:
        - latest
