kind: pipeline
type: kubernetes
name: default

steps:
  - name: docker build
    image: plugins/docker
    failure: always
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: stiforr/ci-tools
      auto_tag: true
      tags:
        - latest

  - name: release
    image: node:17
    commands:
      - yarn install
      - yarn semantic-release
